server:
  port: 10010
spring:
  application:
    name: yintai-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
    register-with-eureka: true
    #取服务注册中心拉取服务的时间间隔
    registry-fetch-interval-seconds: 10
#配置zuul路由
zuul:
  prefix:/api
